package com.efunor.project_l.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskLayerDaoConfig;
    private final DaoConfig taskDetailLayerDaoConfig;

    private final TaskLayerDao taskLayerDao;
    private final TaskDetailLayerDao taskDetailLayerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskLayerDaoConfig = daoConfigMap.get(TaskLayerDao.class).clone();
        taskLayerDaoConfig.initIdentityScope(type);

        taskDetailLayerDaoConfig = daoConfigMap.get(TaskDetailLayerDao.class).clone();
        taskDetailLayerDaoConfig.initIdentityScope(type);

        taskLayerDao = new TaskLayerDao(taskLayerDaoConfig, this);
        taskDetailLayerDao = new TaskDetailLayerDao(taskDetailLayerDaoConfig, this);

        registerDao(TaskLayer.class, taskLayerDao);
        registerDao(TaskDetailLayer.class, taskDetailLayerDao);
    }
    
    public void clear() {
        taskLayerDaoConfig.getIdentityScope().clear();
        taskDetailLayerDaoConfig.getIdentityScope().clear();
    }

    public TaskLayerDao getTaskLayerDao() {
        return taskLayerDao;
    }

    public TaskDetailLayerDao getTaskDetailLayerDao() {
        return taskDetailLayerDao;
    }

}
