package com.efunor.project_l.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK_DETAIL_LAYER".
 */
public class TaskDetailLayer {

    private Long id;
    private String title;
    private String task_id;
    private String parent_id;

    public TaskDetailLayer() {
    }

    public TaskDetailLayer(Long id) {
        this.id = id;
    }

    public TaskDetailLayer(Long id, String title, String task_id, String parent_id) {
        this.id = id;
        this.title = title;
        this.task_id = task_id;
        this.parent_id = parent_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTask_id() {
        return task_id;
    }

    public void setTask_id(String task_id) {
        this.task_id = task_id;
    }

    public String getParent_id() {
        return parent_id;
    }

    public void setParent_id(String parent_id) {
        this.parent_id = parent_id;
    }

}
