package com.efunor.project_l.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK_LAYER".
 */
public class TaskLayer {

    private Long id;
    private String self_id;
    private String parent_id;
    private Long update_time;
    private String tid;
    private Boolean is_indent;
    private Integer order_list;

    public TaskLayer() {
    }

    public TaskLayer(Long id) {
        this.id = id;
    }

    public TaskLayer(Long id, String self_id, String parent_id, Long update_time, String tid, Boolean is_indent, Integer order_list) {
        this.id = id;
        this.self_id = self_id;
        this.parent_id = parent_id;
        this.update_time = update_time;
        this.tid = tid;
        this.is_indent = is_indent;
        this.order_list = order_list;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSelf_id() {
        return self_id;
    }

    public void setSelf_id(String self_id) {
        this.self_id = self_id;
    }

    public String getParent_id() {
        return parent_id;
    }

    public void setParent_id(String parent_id) {
        this.parent_id = parent_id;
    }

    public Long getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public Boolean getIs_indent() {
        return is_indent;
    }

    public void setIs_indent(Boolean is_indent) {
        this.is_indent = is_indent;
    }

    public Integer getOrder_list() {
        return order_list;
    }

    public void setOrder_list(Integer order_list) {
        this.order_list = order_list;
    }

}
